### ISSUE TITLE
'Off' switches off the xiaomi remote

### ISSUE THREAD

**Issue by skywluke** [Anonym-tsk/homeassistant-climate-xiaomi-remote#6]
Hi! It's amazing work! I love it! ;) Little issue, if i click the 'off' button the xiaomi remote controller switch off and doesn't work anymore. (the little blue led goes dark) I don't know, how can i switch it on again.

**Comment by Anonym-tsk** [comment]
Looks like problem with your remote. Try to write 'off' command again and put it to config.
And look at HA logs too.

**Comment by skywluke** [comment]
I rewrite all 3 'off' command. 1 of conf.yaml and 2 of Roda..yaml. Result is same, the blue led goes dark. It's a clean hassio installation. Maybe i put <switch off> command to 16C. I never use it... ;)

**Comment by skywluke** [comment]
Now, it's ok. The problem was the captured code. I captured again, and everything working fine. Another question: If i send commands from automation via "remote.xiaomi_miio_192_168_137_229". Is it possible to set the status of your component to this specific value?

**Comment by Anonym-tsk** [comment]
Use `climate` commands instead of `remote`
