### ISSUE TITLE
[ADD] Swing mode

### ISSUE THREAD

**Issue by thundergreen** [Anonym-tsk/homeassistant-climate-xiaomi-remote#9]
most AC have swing mode. Would be nice adding this feature maybe.

**Comment by eugene-ki** [comment]
It would be nice. I wote for this feature.

**Comment by thundergreen** [comment]
This issue is very old ..hope Dev is still active?

**Comment by Anonym-tsk** [comment]
This will greatly complicate the configuration of the air conditioner. I added swing support but removed it due to various issues.
